name: PR Check

on:
  pull_request:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build and test
        run: |
          export SQLX_OFFLINE=true
          cargo build --verbose
          cargo test --verbose
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v3
      - run: docker build -t ghcr.io/${GITHUB_REPOSITORY}:latest .
