name: Release

on:
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-publish:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/${GITHUB_REPOSITORY}:latest .
      - run: docker tag ghcr.io/${GITHUB_REPOSITORY}:latest ghcr.io/${GITHUB_REPOSITORY}:commit-${GITHUB_SHA:0:8}
      - run: docker push ghcr.io/${GITHUB_REPOSITORY} --all-tags
